services:
  app:
    image: wispy6970/cricket-scheduler
    ports:
      - "3000:3000"
    volumes:
      - cricket-data:/data
    environment:
      - DB_PATH=/data/sqlite.db

volumes:
  cricket-data:
